flipkart_username: testuser@example.com
flipkart_password: P@ssw0rd!

# Amazon credentials
amazon_username: bhanuprakashj7@gmail.com
amazon_password: Bh@nu_1989

# SauceDemo demo credentials (public test site)
saucedemo_username: standard_user
saucedemo_password: secret_sauce
saucedemo_first_name: Bhanu Prakash
saucedemo_last_name: Joshi
saucedemo_postal_code: 263139
card_number: 4111111111111111
card_name: Test User
card_exp: 12/30
card_cvv: 123
